Navbar
devsoc-unsw/trainee-woodelf-24t2 pull request #10
Opened 2024-07-28 08:10 UTC by xleonx0x

added navbar items

2024-07-30 03:09 UTC, lachlanshoesmith requested changes

2024-07-30 03:09 UTC, lachlanshoesmith commented on frontend/src/components/Navbar/Navbar.tsx
indentation is a little consistent, ensure you run this through prettier

2024-07-30 03:17 UTC, xleonx0x commented on frontend/src/components/Navbar/Navbar.tsx
I'm not too familiar with prettier, could you walk me through 😔

2024-07-30 03:22 UTC, lachlanshoesmith commented on frontend/src/components/Navbar/Navbar.tsx
1. merge in latest changes from main to this branch, which will update both package.jsons to include some prettier config
2. install prettier extension in vscode
3. in vscode config, set `editor: default formatter` to prettier
4. enable `editor: format on save`
5. save the troublesome file and the formatting should fix itself

2024-08-02 13:46 UTC, xleonx0x commented on frontend/src/components/Navbar/Navbar.tsx
> merge in latest changes from main to this branch, which will update both package.jsons to include some prettier config
how do i exactly do this, i don't wanna mess up anything

2024-08-02 13:48 UTC, lachlanshoesmith commented on frontend/src/components/Navbar/Navbar.tsx
`git merge main` should do it

2024-08-02 14:00 UTC, xleonx0x commented on frontend/src/components/Navbar/Navbar.tsx
done 👍

2024-08-02 14:03 UTC, lachlanshoesmith approved these changes

2024-08-02 14:03 UTC, merged