credits prototype
devsoc-unsw/trainee-woodelf-24t2 pull request #20
Opened 2024-08-20 11:20 UTC by xleonx0x

click le button to show le credits

2024-08-20 15:12 UTC, lachlanshoesmith commented on frontend/src/components/Credits/Credits.tsx
> +            <li>Lachlan Shoesmith: Master of Yapping</li>
lol

2024-08-20 15:14 UTC, lachlanshoesmith requested changes

2024-08-20 15:14 UTC, lachlanshoesmith commented on frontend/src/components/Credits/Credits.tsx
> +            <li>Oswaldo Prajitno: </li>
osvaldo

2024-08-20 15:14 UTC, lachlanshoesmith commented on frontend/src/components/Credits/Credits.tsx
> +            <li>Ben Goldwin: </li>
godwin

2024-08-20 15:14 UTC, lachlanshoesmith commented on frontend/src/components/Credits/Credits.tsx
> +        <div className={classes.title}>Credits</div>
make it a h1 dood

2024-08-20 15:14 UTC, lachlanshoesmith commented on frontend/src/components/Navbar/Navbar.tsx
> +      {showCredits &&
i do worry this approach is a bit less readable than just using a native <dialog> but its all good

2024-08-20 22:38 UTC, xleonx0x commented on frontend/src/components/Credits/Credits.tsx
> +        <div className={classes.title}>Credits</div>
ok dood

2024-08-21 01:48 UTC, lachlanshoesmith approved these changes

2024-08-21 01:48 UTC, lachlanshoesmith approved these changes

2024-08-21 01:48 UTC, lachlanshoesmith approved these changes

2024-08-21 01:49 UTC, merged