Login backend
devsoc-unsw/trainee-woodelf-24t2 pull request #23
Opened 2024-08-21 15:24 UTC by xleonx0x

used bcrypt for hashing #️⃣

2024-08-21 16:02 UTC, xleonx0x commented
**note** haven't had time to test it with database data so probably best to hold off merging until that can happen

2024-08-24 12:07 UTC, xleonx0x commented
Haven't implemented tokens yet, but feel free to still look at the database lookup for matching pass / user for register and login

2024-08-25 15:27 UTC, lachlanshoesmith requested changes
this looks good so far!

2024-08-25 15:27 UTC, lachlanshoesmith commented on backend/src/index.ts
> +  const hashedPassword: string = await bcrypt.hash(password, saltRounds);
although bcrypt adds one too, i'd recommend that we add a random [salt](https://en.wikipedia.org/wiki/Salt_(cryptography)) to the password ourselves as well while hashing for extra security. this salt can then be stored in the user obj in the db

2024-08-25 15:27 UTC, lachlanshoesmith commented on backend/src/index.ts
> +  bcrypt.compare(password, details.docs[0].data().password, (err, result) => {
just note that if we add a salt above, we'll also need to add it here to the entered pw

2024-08-25 15:27 UTC, lachlanshoesmith commented on backend/src/index.ts
> +app.get("/colour", async (req, res) => {
u can delete this haha

2024-08-25 16:59 UTC, xleonx0x commented on backend/src/index.ts
> +  const hashedPassword: string = await bcrypt.hash(password, saltRounds);
so we salt the password + salt it with bcrypt again?

2024-08-26 05:38 UTC, lachlanshoesmith commented on backend/src/index.ts
> +  const hashedPassword: string = await bcrypt.hash(password, saltRounds);
yes please! this doesnt make a huge difference to our security really - diminishing returns - *but* it's a common practice you'll likely follow when encrypting/hashing with other libraries in the future

2024-08-27 04:45 UTC, lachlanshoesmith approved these changes

2024-08-27 04:45 UTC, merged