Take in a level id and return the level object endpoint
devsoc-unsw/trainee-woodelf-24t2 pull request #38
Opened 2024-09-09 14:26 UTC by alyssacheong

2024-09-09 15:20 UTC, bengodw reviewed
works perfect - I forgot to say though that this endpoint will also need to return the hotspots for the level, so you will need to create a hotspot interface (you can just copy this from the db), add an array of hotspots to the level and make it so that this endpoint also adds the hotspots to the level. This isn't a massive priority (like game still 'works' without hotspots) but I think Chris is implementing them on the frontend so would be good. Completely my fault for forgetting to raise this earlier.

2024-09-10 05:20 UTC, lachlanshoesmith requested changes
i think yellowbutton-related files can be deleted atp but i might be wrong

2024-09-10 05:20 UTC, lachlanshoesmith commented on backend/src/interfaces.ts
> +  id?: string;
is this ever undefined?

2024-09-10 05:20 UTC, lachlanshoesmith commented on backend/src/interfaces.ts
> +  locationName: string | undefined;
every hotspot shoulllld have a name associated with it

2024-09-10 09:10 UTC, bengodw approved these changes

2024-09-10 09:15 UTC, merged